In [1]:
import numpy as np

In [2]:
python_list = [1,2,3,5,-5]

In [3]:
python_list

[1, 2, 3, 5, -5]

In [5]:
numpy_arr = np.array(python_list)

In [7]:
len(numpy_arr.shape)

1

In [8]:
python_list_list = [[1,2],[3,4]]

In [9]:
python_list_list

[[1, 2], [3, 4]]

In [11]:
numpy_arr2 = np.array(python_list_list)

In [13]:
len(numpy_arr2.shape)

2

In [14]:
numpy_arr2.shape

(2, 2)

In [15]:
python_list_list = [[1,2,5],[3,4,7]]

In [16]:
np.array(python_list_list).shape

(2, 3)

In [18]:
list(range(5))

[0, 1, 2, 3, 4]

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
np.random.randint(5, size=(2,2))

array([[0, 4],
       [1, 2]])